# Notebook for data cleaning

## 0- Loading useful packages

In [2]:
import pandas as pd
import ast

## 1- Loading the full data

In [3]:
current_full_data = pd.read_csv("current_full_dataset_v2.csv")

In [4]:
cleaned_data = current_full_data.copy()

In [5]:
# number of distinct documents analysed
n_documents = len(pd.unique(cleaned_data['url']))
n_documents

159

In [6]:
cleaned_data = cleaned_data.drop(columns=['index'])
print(cleaned_data.columns)

Index(['url', 'title', 'authors', 'date', 'extract', 'country', 'theme'], dtype='str')

In [7]:
# checking for duplicate rows
duplicates = cleaned_data[cleaned_data[['url', 'extract']].duplicated()]
len(duplicates)

0

In [8]:
duplicates = cleaned_data[cleaned_data['extract'].duplicated()]
len(duplicates)

38

In [9]:
# 38 rows are duplicated, checking which urls they come from
pd.unique(duplicates['url'])

<ArrowStringArray>
[                                                                                                                      'https://www.scielo.org.za/scielo.php?pid=S1996-20962019000100013&script=sci_arttext',
                                                                                                  'https://www.ohchr.org/sites/default/files/Documents/Issues/Albinism/Albinism_Worldwide_Report2021_EN.pdf',
                                                                                                                                  'https://unicri.org/sites/default/files/2019-10/IOM_PWA_REPORT_ENG_P2.pdf',
                                                                                                         'https://www.underthesamesun.com/wp-content/uploads/2024/09/Attacks-of-PWA-Extended-02.09.2024.pdf',
                                                                                                                    'https://www.underthesamesun.com/wp-content/uploads/2022/08/Attacks-of-PWA-Extended.pdf',
                                                                           'http://rodra.co.za/images/countries/kenya/research/UPR%20The%20Human%20Rights%20of%20Persons%20with%20Albinism%20in%20Kenya.pdf',
 'https://africaalbinismnetwork.org/wp-content/uploads/2026/06/Press-Release-Malawi-People-with-Albinism-Face-Discrimination-Barriers-to-Work-Stigma-Insecurity-Lack-of-Accommodations-Undermine-Rights.pdf',
                                                                                                                                                          'https://www.bbc.co.uk/news/world-africa-66221755',
                                                                                                                 'https://upr-info.org/sites/default/files/documents/2015-01/js10_-_joint_submission_10.pdf',
                                                                               'https://www.newsday.co.zw/local-news/article/200049903/people-with-albinism-recount-stigma-myths-fear-of-murder-for-rituals']
Length: 10, dtype: str

In [10]:
# dropping the rows with the duplicated urls, as they come from documents that have been analysed twice
cleaned_data = cleaned_data[cleaned_data['url'].apply(lambda x: x not in pd.unique(duplicates['url']))]

In [11]:
duplicates = cleaned_data[cleaned_data['extract'].duplicated()]
len(duplicates)

0

In [12]:
# number of distinct documents analysed
n_documents = len(pd.unique(cleaned_data['url']))
n_documents

149

## title

In [13]:
# number of lines with no title
n_no_title = cleaned_data[cleaned_data['title'].isna()]['title'].count()
n_no_title

np.int64(0)

In [14]:
n_dif_titles = len(pd.unique(cleaned_data['title']))
n_dif_titles

145

In [15]:
df_url_title = cleaned_data[['title', 'url']]
distincts_url_titles = df_url_title.drop_duplicates()

In [16]:
distincts_url_titles['title'].value_counts()

title
ACCESS TO JUSTICE FOR PERSONS WITH ALBINISM: CHALLENGES AND SOLUTIONS IN ZAMBIA                                                                                2
Securing health and wellbeing for children with albinism                                                                                                       2
People With Albinism Face Discrimination, Danger                                                                                                               2
Oral Statement of the International Commission of Jurists (ICJ) in the Interactive Dialogue with the Independent Expert on Albinism                            2
Attacks on people with albinism in Tanzania: African court holds government responsible – why it matters                                                       1
                                                                                                                                                              ..
Persons with albinism plead for skills training, startup loans - Malawi News | Breaking News, Politics, Business & Sports | Nyasa Times                        1
Submission in response to the call for inputs: Persons with Albinism and the rights to education                                                               1
Bullying and Exclusion of Children with Albinism in the School Systems of Sub-Saharan Africa: An Exploratory Study at an Inclusive Model School in Tanzania    1
Children with albinism in African regions: their rights to ‘being’ and ‘doing’                                                                                 1
Exploring barriers to learning hindering Learners with albinism’ academic achievement at schools in the Masvingo district in Zimbabwe                          1
Name: count, Length: 145, dtype: int64

In [17]:
problem = cleaned_data[cleaned_data['title'] == "ACCESS TO JUSTICE FOR PERSONS WITH ALBINISM: CHALLENGES AND SOLUTIONS IN ZAMBIA"]
problem['url'].value_counts()

url
https://africaalbinismnetwork.org/wp-content/uploads/2025/04/access-justice-person-with-albinism.pdf        31
https://www.ohchr.org/sites/default/files/documents/publications/access-justice-person-with-albinism.pdf    27
Name: count, dtype: int64

In [18]:
# dropping rows from the second url
cleaned_data = cleaned_data[cleaned_data['url'] != "https://www.ohchr.org/sites/default/files/documents/publications/access-justice-person-with-albinism.pdf"]

In [19]:
problem = cleaned_data[cleaned_data['title'] == "Securing health and wellbeing for children with albinism"]
problem['url'].value_counts()

url
https://repository.up.ac.za/bitstreams/da109116-58c9-4d8a-ba3c-881ea8e6621a/download    3
https://doi.org/10.1016/s2352-4642(24)00136-6                                           2
Name: count, dtype: int64

In [20]:
# changing the date of the first url to the one of the second
cleaned_data.loc[cleaned_data['url'] == "https://repository.up.ac.za/bitstreams/da109116-58c9-4d8a-ba3c-881ea8e6621a/download", "date"] = "13/06/2024"

# removing the data collected for the second url
cleaned_data = cleaned_data[cleaned_data['url'] != "https://doi.org/10.1016/s2352-4642(24)00136-6"]

In [21]:
problem = cleaned_data[cleaned_data['title'] == "Oral Statement of the International Commission of Jurists (ICJ) in the Interactive Dialogue with the Independent Expert on Albinism"]
problem['url'].value_counts()

url
https://www.icj.org/wp-content/uploads/2025/03/ICJ-OS-ID-IE-Albinism-HRC-58.pdf                  1
https://africaalbinismnetwork.org/wp-content/uploads/2025/03/ICJ-OS-ID-IE-Albinism-HRC-58.pdf    1
Name: count, dtype: int64

In [22]:
cleaned_data = cleaned_data[cleaned_data['url'] != "https://africaalbinismnetwork.org/wp-content/uploads/2025/03/ICJ-OS-ID-IE-Albinism-HRC-58.pdf"]

In [23]:
problem = cleaned_data[cleaned_data['title'] == "People With Albinism Face Discrimination, Danger"]
problem['url'].value_counts()

url
https://www.hrw.org/news/2026/06/12/people-with-albinism-face-discrimination-danger    2
https://www.ipsnews.net/2026/06/people-with-albinism-face-discrimination-danger/       1
Name: count, dtype: int64

In [24]:
cleaned_data = cleaned_data[cleaned_data['url'] != "https://www.hrw.org/news/2026/06/12/people-with-albinism-face-discrimination-danger"]

In [25]:
df_url_title = cleaned_data[['title', 'url']]
distincts_url_titles = df_url_title.drop_duplicates()
distincts_url_titles['title'].value_counts()

title
Attacks on people with albinism in Tanzania: African court holds government responsible – why it matters                                                       1
The Witchcraft Act and the Cost of Inaction: AfCHPR on the Persecution of Persons with Albinism                                                                1
A STEP TO ZERO ATTACKS: REFLECTIONS ON THE RIGHTS OF PERSONS WITH ALBINISM THROUGH THE LENS OF X V UNITED REPUBLIC OF TANZANIA                                 1
SOUTHERN AFRICA JOURNAL ON ALBINISM AND SOCIO-ECONOMIC RIGHTS                                                                                                  1
ACCESS TO JUSTICE FOR PERSONS WITH ALBINISM: CHALLENGES AND SOLUTIONS IN ZAMBIA                                                                                1
                                                                                                                                                              ..
Persons with albinism plead for skills training, startup loans - Malawi News | Breaking News, Politics, Business & Sports | Nyasa Times                        1
Submission in response to the call for inputs: Persons with Albinism and the rights to education                                                               1
Bullying and Exclusion of Children with Albinism in the School Systems of Sub-Saharan Africa: An Exploratory Study at an Inclusive Model School in Tanzania    1
Children with albinism in African regions: their rights to ‘being’ and ‘doing’                                                                                 1
Exploring barriers to learning hindering Learners with albinism’ academic achievement at schools in the Masvingo district in Zimbabwe                          1
Name: count, Length: 145, dtype: int64

In [26]:
len(cleaned_data)

558

## authors

In [27]:
# number of distinct documents analysed
n_documents = len(pd.unique(cleaned_data['url']))
n_documents

145

In [28]:
# number of distinct authors
n_authors = len(pd.unique(cleaned_data['authors']))
n_authors

101

In [29]:
# documents with no authors seemingly
df_url_authors = cleaned_data[['authors', 'url']]
distincts_url_authors = df_url_authors.drop_duplicates()

In [30]:
distincts_url_authors[distincts_url_authors["authors"].isna()]['url']

81     https://malawi24.com/2026/01/18/even-in-death-...
92     https://www.un.org/en/observances/albinism-day...
142    https://unicri.org/situation-analysis-human-ri...
148    https://africaalbinismnetwork.org/blog/angola-...
157    https://www.voanews.com/a/un-concerned-about-m...
158    https://upr-info.org/sites/default/files/count...
167    https://www.iwacu-burundi.org/englishnews/disc...
178    https://www.africanews.com/2021/12/06/cameroon...
186    https://www.voanews.com/a/cameroons-albinos-fi...
311    https://www.chr.up.ac.za/news-archive/2018/485...
312    https://www.africanews.com/2021/11/21/congo-br...
428    https://www.hrw.org/news/2025/04/17/ensuring-e...
506    https://www.eswatiniobserver.com/7-children-wi...
529    https://www.albinismalliance.org/news/living-w...
548    https://www.graphic.com.gh/news/general-news/g...
557    https://www.hi-canada.org/en/news/aicha-and-fr...
581    https://www.ohchr.org/en/press-releases/2024/0...
582    https://www.africa-press.net/lesotho/all-news/...
601    https://liberties.aljazeera.com/en/in-malawi-b...
626    https://www.hrw.org/video-photos/video/2019/06...
627    https://360mozambique.com/development/governme...
631    https://clubofmozambique.com/news/mozambique-g...
640    https://collaborativemedia.wscij.org/nigeria-a...
653    https://www.dw.com/en/senegal-albinos-want-the...
673    https://radioergo.org/en/2023/05/albinos-livin...
680    https://radioergo.org/en/2024/01/albino-childr...
682    https://radioergo.org/en/2019/06/albinos-face-...
711    https://www.ohchr.org/en/press-releases/2025/0...
723    https://www.thecitizen.co.tz/tanzania/news/cou...
730    https://www.africanews.com/2026/06/24/tunisia-...
781    https://www.world-today-news.com/malawis-new-a...
782    https://www.nyasatimes.com/persons-with-albini...
Name: url, dtype: str

In [31]:
cleaned_data = cleaned_data[cleaned_data["url"] != "https://www.africanews.com/2026/06/24/tunisia-upholds-eight-year-jail-term-for-anti-racism-activist/"]

In [32]:
cleaned_data.loc[cleaned_data['url'] == "https://malawi24.com/2026/01/18/even-in-death-albinism-victims-are-not-safe/", "authors"] = "Eric Chiputula"
cleaned_data.loc[cleaned_data['url'] == "https://www.un.org/en/observances/albinism-day/albinism-and-human-rights", "authors"] = "United Nations"
cleaned_data.loc[cleaned_data['url'] == "https://africaalbinismnetwork.org/blog/angola-adopts-national-action-plan-on-albinism-after-six-years-of-relentless-advocacy/", "authors"] = "Africa Albinism Network (ANN)"
cleaned_data.loc[cleaned_data['url'] == "https://www.voanews.com/a/un-concerned-about-minority-group-discrimination-in-benin-zimbabwe/6726715.html", "authors"] = "Lisa Schlein"
cleaned_data.loc[cleaned_data['url'] == "https://www.iwacu-burundi.org/englishnews/discrimination-and-skin-diseases-pose-major-threat-to-burundian-albinos/", "authors"] = "Diane Uwimana"
cleaned_data.loc[cleaned_data['url'] == "https://www.chr.up.ac.za/news-archive/2018/485-pan-african-parliament-takes-a-strong-stance-on-violence-against-persons-with-albinism-in-africa", "authors"] = "Khumalo Simphiwe"
cleaned_data.loc[cleaned_data['url'] == "https://www.hrw.org/news/2025/04/17/ensuring-essential-sun-protection-persons-albinism", "authors"] = "Samer Muscati"
cleaned_data.loc[cleaned_data['url'] == "https://www.eswatiniobserver.com/7-children-with-albinism-face-discrimination/", "authors"] = "Musa Simelane"
cleaned_data.loc[cleaned_data['url'] == "https://www.graphic.com.gh/news/general-news/ghana-news-international-albinism-awareness-day-2025-health-legal-reforms-needed-to-save-lives-of-persons-with-albinism-advocate.html", "authors"] = "Dickson Worlanyo Dotse"
cleaned_data.loc[cleaned_data['url'] == "https://www.dw.com/en/senegal-albinos-want-their-own-sunscreen-factory/a-19181372", "authors"] = "Emmanuelle Landais"
cleaned_data.loc[cleaned_data['url'] == "https://www.thecitizen.co.tz/tanzania/news/court-news/tanzania-ordered-to-revise-witchcraft-laws-to-protect-people-with-albinism-4913926", "authors"] = "Bertha Ismail"
cleaned_data.loc[cleaned_data['url'] == "https://www.world-today-news.com/malawis-new-action-plan-aims-to-end-economic-exclusion-for-people-with-albinism/", "authors"] = "Lucas Fernandez"
cleaned_data.loc[cleaned_data['url'] == "https://www.nyasatimes.com/persons-with-albinism-plead-for-skills-training-startup-loans/", "authors"] = "Watipaso Mzungu"

In [33]:
df_url_authors = cleaned_data[['authors', 'url']]
distincts_url_authors = df_url_authors.drop_duplicates()
distincts_url_authors[distincts_url_authors["authors"].isna()]['url']

142    https://unicri.org/situation-analysis-human-ri...
158    https://upr-info.org/sites/default/files/count...
178    https://www.africanews.com/2021/12/06/cameroon...
186    https://www.voanews.com/a/cameroons-albinos-fi...
312    https://www.africanews.com/2021/11/21/congo-br...
529    https://www.albinismalliance.org/news/living-w...
557    https://www.hi-canada.org/en/news/aicha-and-fr...
581    https://www.ohchr.org/en/press-releases/2024/0...
582    https://www.africa-press.net/lesotho/all-news/...
601    https://liberties.aljazeera.com/en/in-malawi-b...
626    https://www.hrw.org/video-photos/video/2019/06...
627    https://360mozambique.com/development/governme...
631    https://clubofmozambique.com/news/mozambique-g...
640    https://collaborativemedia.wscij.org/nigeria-a...
673    https://radioergo.org/en/2023/05/albinos-livin...
680    https://radioergo.org/en/2024/01/albino-childr...
682    https://radioergo.org/en/2019/06/albinos-face-...
711    https://www.ohchr.org/en/press-releases/2025/0...
Name: url, dtype: str

## dates

In [34]:
# number of distinct documents analysed
n_documents = len(pd.unique(cleaned_data['url']))
n_documents

144

In [35]:
# number of distinct dates
n_dates = len(pd.unique(cleaned_data['date']))
n_dates

87

In [36]:
# documents with no date seemingly
df_url_dates = cleaned_data[['date', 'url']]
distincts_url_dates = df_url_dates.drop_duplicates()

In [37]:
distincts_url_dates[distincts_url_dates["date"].isna()]['url']

0      https://theconversation.com/attacks-on-people-...
81     https://malawi24.com/2026/01/18/even-in-death-...
92     https://www.un.org/en/observances/albinism-day...
110    https://csjnews.org/article/people-with-albini...
142    https://unicri.org/situation-analysis-human-ri...
145    https://angop.ao/en/noticias/grandes-reportage...
149    https://africaalbinismnetwork.org/wp-content/u...
157    https://www.voanews.com/a/un-concerned-about-m...
158    https://upr-info.org/sites/default/files/count...
165    https://www.sosmediasburundi.org/en/2024/05/25...
167    https://www.iwacu-burundi.org/englishnews/disc...
170    https://www.iwacu-burundi.org/englishnews/buru...
174    https://www.africaninsider.com/news/albino-chi...
178    https://www.africanews.com/2021/12/06/cameroon...
305    https://www.icj.org/wp-content/uploads/2025/03...
311    https://www.chr.up.ac.za/news-archive/2018/485...
312    https://www.africanews.com/2021/11/21/congo-br...
313    https://news.abidjan.net/articles/411536/inter...
428    https://www.hrw.org/news/2025/04/17/ensuring-e...
548    https://www.graphic.com.gh/news/general-news/g...
549    https://guineenews.org/2019/08/19/dossier-afri...
553    https://www.sitesofconscience.org/extraordinar...
556    https://zap.aeiou.pt/os-albinos-da-guine-bissa...
557    https://www.hi-canada.org/en/news/aicha-and-fr...
583    https://reports231.com/albinism-society-critic...
585       https://www.state.gov/report/custom/1948f83df1
588    https://www.amnesty.org/en/latest/campaigns/20...
610    https://www.newsweek.com/albino-girl-killed-al...
611    https://africanlii.org/articles/2019-09-11/SAL...
615    https://albinism.ohchr.org/story-salif-keita.html
631    https://clubofmozambique.com/news/mozambique-g...
634    https://abcdocz.com/doc/56660/customary-practi...
647    https://umuringanews.com/climate-change-and-al...
653    https://www.dw.com/en/senegal-albinos-want-the...
654    http://albinossenegal.blogspot.com/2011/04/rep...
657    https://lequotidien.sn/manque-de-prise-en-char...
671    https://manoreporters.com/news/health/sierra-l...
673    https://radioergo.org/en/2023/05/albinos-livin...
680    https://radioergo.org/en/2024/01/albino-childr...
682    https://radioergo.org/en/2019/06/albinos-face-...
694    https://joining-forces.org/joining-forces-for-...
723    https://www.thecitizen.co.tz/tanzania/news/cou...
747    https://africaalbinismnetwork.org/wp-content/u...
751    https://africaalbinismnetwork.org/wp-content/u...
762    https://matebelelandpulse.co.zw/2025/02/19/zim...
776    https://ihrp.law.utoronto.ca/un-advocacy-cockt...
781    https://www.world-today-news.com/malawis-new-a...
782    https://www.nyasatimes.com/persons-with-albini...
784    https://africaalbinismnetwork.org/wp-content/u...
Name: url, dtype: str

In [38]:
cleaned_data.loc[cleaned_data['url'] == "https://theconversation.com/attacks-on-people-with-albinism-in-tanzania-african-court-holds-government-responsible-why-it-matters-251275", "date"] = "12/03/2025"
cleaned_data.loc[cleaned_data['url'] == "https://malawi24.com/2026/01/18/even-in-death-albinism-victims-are-not-safe/", "date"] = "18/01/2026"
cleaned_data.loc[cleaned_data['url'] == "https://csjnews.org/article/people-with-albinism-in-malawi-face-discrimination-and-economic-exclusion", "date"] = "16/06/2026"
cleaned_data.loc[cleaned_data['url'] == "https://angop.ao/en/noticias/grandes-reportagens/pessoas-com-albinismo-condenadas-pela-ignorancia/", "date"] = "10/06/2026"
cleaned_data.loc[cleaned_data['url'] == "https://www.voanews.com/a/un-concerned-about-minority-group-discrimination-in-benin-zimbabwe/6726715.html", "date"] = "01/09/2022"
cleaned_data.loc[cleaned_data['url'] == "https://upr-info.org/sites/default/files/country-document/2022-12/CBDH_Statement_Presession42_Benin.pdf", "date"] = "12/2022"
cleaned_data.loc[cleaned_data['url'] == "https://www.sosmediasburundi.org/en/2024/05/25/giharo-six-people-accused-of-desecrating-the-grave-of-an-albino-arrested/", "date"] = "25/05/2024"
cleaned_data.loc[cleaned_data['url'] == "https://www.iwacu-burundi.org/englishnews/discrimination-and-skin-diseases-pose-major-threat-to-burundian-albinos/", "date"] = "13/06/2018"
cleaned_data.loc[cleaned_data['url'] == "https://www.iwacu-burundi.org/englishnews/burundi-albinos-discrimination-a-sad-situation/", "date"] = "09/12/2013"
cleaned_data.loc[cleaned_data['url'] == "https://www.africaninsider.com/news/albino-child-dismembered-in-burundi-association-says/", "date"] = "02/02/2022"
cleaned_data.loc[cleaned_data['url'] == "https://www.africanews.com/2021/12/06/cameroon-s-albinos-threatened-by-magic-and-superstition/", "date"] = "13/08/2024"
cleaned_data.loc[cleaned_data['url'] == "https://www.icj.org/wp-content/uploads/2025/03/ICJ-OS-ID-IE-Albinism-HRC-58.pdf", "date"] = "03/2025"
cleaned_data.loc[cleaned_data['url'] == "https://www.chr.up.ac.za/news-archive/2018/485-pan-african-parliament-takes-a-strong-stance-on-violence-against-persons-with-albinism-in-africa", "date"] = "22/05/2018"
cleaned_data.loc[cleaned_data['url'] == "https://www.africanews.com/2021/11/21/congo-brazzaville-clinic-helps-embattled-albino-minority/", "date"] = "13/08/2024"
cleaned_data.loc[cleaned_data['url'] == "https://news.abidjan.net/articles/411536/interview-coulibaly-mamidou-lalbinos-denonce-nous-sommes-en-danger-en-periodes-electorales", "date"] = "24/09/2011"
cleaned_data.loc[cleaned_data['url'] == "https://www.hrw.org/news/2025/04/17/ensuring-essential-sun-protection-persons-albinism", "date"] = "17/04/2025"
cleaned_data.loc[cleaned_data['url'] == "https://www.graphic.com.gh/news/general-news/ghana-news-international-albinism-awareness-day-2025-health-legal-reforms-needed-to-save-lives-of-persons-with-albinism-advocate.html", "date"] = "20/06/2025"
cleaned_data.loc[cleaned_data['url'] == "https://guineenews.org/2019/08/19/dossier-afrique-et-albinisme-persecutions-exclusion-trafic-dorganes-crimes-rituels-insertion-le-dur-quotidien-des-albinos-en-guinee/", "date"] = "19/08/2019"
cleaned_data.loc[cleaned_data['url'] == "https://zap.aeiou.pt/os-albinos-da-guine-bissau-querem-protecao-do-estado-569031", "date"] = "23/11/2023"
cleaned_data.loc[cleaned_data['url'] == "https://www.amnesty.org/en/latest/campaigns/2026/07/ending-attacks-against-persons-with-albinism/", "date"] = "10/07/2026"
cleaned_data.loc[cleaned_data['url'] == "https://www.newsweek.com/albino-girl-killed-albinism-mali-election-superstition-ritual-albinism-police-927200", "date"] = "15/05/2018"
cleaned_data.loc[cleaned_data['url'] == "https://africanlii.org/articles/2019-09-11/SALC/statement-shining-a-light-on-the-urgency-of-implementing-the-regional-action-plan-on-albinism-in-africa", "date"] = "11/09/2019"
cleaned_data.loc[cleaned_data['url'] == "https://clubofmozambique.com/news/mozambique-gang-of-four-amputates-arm-of-albino-teenager-in-ile/", "date"] = "04/12/2023"
cleaned_data.loc[cleaned_data['url'] == "https://umuringanews.com/climate-change-and-albinism-the-struggles-of-people-with-albinism-in-rwanda/", "date"] = "31/01/2025"
cleaned_data.loc[cleaned_data['url'] == "https://www.dw.com/en/senegal-albinos-want-their-own-sunscreen-factory/a-19181372", "date"] = "04/12/2016"
cleaned_data.loc[cleaned_data['url'] == "http://albinossenegal.blogspot.com/2011/04/report-of-situation-of-albinos-in.html", "date"] = "11/04/2011"
cleaned_data.loc[cleaned_data['url'] == "https://lequotidien.sn/manque-de-prise-en-charge-stigmatisation-la-lutte-brulante-des-albinos/", "date"] = "12/04/2025"
cleaned_data.loc[cleaned_data['url'] == "https://radioergo.org/en/2023/05/albinos-living-with-stigma-and-poverty-in-somalia/", "date"] = "31/05/2023"
cleaned_data.loc[cleaned_data['url'] == "https://radioergo.org/en/2024/01/albino-children-in-dadaab-refugee-camp-are-stung-by-insults-and-stones/", "date"] = "31/01/2024"
cleaned_data.loc[cleaned_data['url'] == "https://radioergo.org/en/2019/06/albinos-face-attacks-and-rejection-in-somali-refugee-camps-in-dadaab/", "date"] = "18/06/2019"
cleaned_data.loc[cleaned_data['url'] == "https://www.thecitizen.co.tz/tanzania/news/court-news/tanzania-ordered-to-revise-witchcraft-laws-to-protect-people-with-albinism-4913926", "date"] = "5/02/2025"
cleaned_data.loc[cleaned_data['url'] == "https://africaalbinismnetwork.org/wp-content/uploads/2026/01/Joint-Shadow-Report-to-the-CESCR-Human-Rights-situation-of-Persons-with-Albinism-in-Zambia.pdf", "date"] = "01/2026"
cleaned_data.loc[cleaned_data['url'] == "https://africaalbinismnetwork.org/wp-content/uploads/2024/02/Report-on-the-situation-of-persons-with-albinism-in-Zambia-to-the-CRPD-12.02.2024.pdf", "date"] = "12/02/2024"
cleaned_data.loc[cleaned_data['url'] == "https://matebelelandpulse.co.zw/2025/02/19/z", "date"] = "19/02/2025"
cleaned_data.loc[cleaned_data['url'] == "https://www.world-today-news.com/malawis-new-action-plan-aims-to-end-economic-exclusion-for-people-with-albinism/", "date"] = "24/06/2026"
cleaned_data.loc[cleaned_data['url'] == "https://www.nyasatimes.com/persons-with-albinism-plead-for-skills-training-startup-loans/", "date"] = "28/11/2022"
cleaned_data.loc[cleaned_data['url'] == "https://africaalbinismnetwork.org/wp-content/uploads/2023/11/Joint-submission-in-Response-to-the-Call-for-Inputs-Persons-with-Albinism-and-the-Right-to-Education.pdf", "date"] = "11/2023"

In [39]:
df_url_dates = cleaned_data[['date', 'url']]
distincts_url_dates = df_url_dates.drop_duplicates()
distincts_url_dates[distincts_url_dates["date"].isna()]['url']

92     https://www.un.org/en/observances/albinism-day...
142    https://unicri.org/situation-analysis-human-ri...
149    https://africaalbinismnetwork.org/wp-content/u...
553    https://www.sitesofconscience.org/extraordinar...
557    https://www.hi-canada.org/en/news/aicha-and-fr...
583    https://reports231.com/albinism-society-critic...
585       https://www.state.gov/report/custom/1948f83df1
615    https://albinism.ohchr.org/story-salif-keita.html
634    https://abcdocz.com/doc/56660/customary-practi...
671    https://manoreporters.com/news/health/sierra-l...
694    https://joining-forces.org/joining-forces-for-...
762    https://matebelelandpulse.co.zw/2025/02/19/zim...
776    https://ihrp.law.utoronto.ca/un-advocacy-cockt...
Name: url, dtype: str

In [40]:
len(cleaned_data)

556

In [41]:
len(pd.unique(cleaned_data['url']))

144

## countries

In [42]:
# printing the distinct combinations of countries
cleaned_data['country'].value_counts()

country
[]                    195
['Tanzania']           45
['Zambia']             23
['South Africa']       14
['Namibia']            14
                     ...
['Perú', 'Zambia']      1
['Argentina']           1
[None, 'Malawi']        1
['Brasil', None]        1
['Hrvatska']            1
Name: count, Length: 116, dtype: int64

In [43]:
cleaned_data["country"].map(type).unique()

array([<class 'str'>], dtype=object)

In [44]:
cleaned_data['country'] = cleaned_data["country"].apply(ast.literal_eval)

In [45]:
cleaned_data["country"].map(type).unique()

array([<class 'list'>], dtype=object)

In [46]:
TO_REMOVE = [None, "Sri Lanka", "中国", "United States",
             "Suomi / Finland", "Monaco", "မြန်မာ", "România",
             "Philippines", "Norge", "Colombia", "Brasil",
             "မြန်မာ", "日本", "France", "India", "Danmark",
             "Tonga", "Argentina", "New Zealand / Aotearoa",
             "ประเทศไทย", "Italia", "Deutschland", "Canada",
             "België / Belgique / Belgien", "Nederland",
             "Papua Niugini", "Australia", "ປະເທດລາວ", "Malaysia",
             "پاکستان", "Perú", "Hrvatska"
             ]

currently_identified = []

cleaned_data["to_watch"] = False

for index, _ in cleaned_data.iterrows():

    country_list = cleaned_data.loc[index, 'country']
    cleaned_country_list = []

    PROBLEM = False

    for item in country_list:

        if item not in TO_REMOVE:
            cleaned_country_list.append(item)

            if item not in currently_identified:
                currently_identified.append(item)
    
    cleaned_data.at[index, 'country'] = cleaned_country_list

    if len(country_list) != len(cleaned_country_list):
        PROBLEM = True

    cleaned_data.at[index, 'to_watch'] = PROBLEM

In [47]:
currently_identified

['Tanzania',
 'South Africa',
 'Zambia',
 'République démocratique du Congo',
 'Malawi',
 'Moçambique',
 'Nigeria',
 'Uganda',
 'Ghana',
 'Namibia',
 'Kenya',
 'Angola',
 'Bénin',
 'Rwanda',
 'Burundi',
 'Zimbabwe',
 'Cameroun',
 'Botswana',
 'Burkina Faso',
 'مصر',
 'Gabon',
 'Sénégal',
 'Guinée',
 'تونس',
 'Lesotho',
 'Madagasikara / Madagascar',
 'Liberia',
 'Mali',
 'Sierra Leone',
 'Niger',
 'Eswatini',
 'Congo',
 'Côte d’Ivoire',
 'Gambia',
 'Djibouti جيبوتي',
 'Mauritanie موريتانيا',
 'Soomaaliya الصومال',
 'South Sudan جنوب السودان',
 'Togo']

In [48]:
cleaned_data['country'].value_counts()

country
[]                                                     237
[Tanzania]                                              48
[Zambia]                                                44
[Ghana]                                                 17
[Kenya]                                                 17
[South Africa]                                          15
[Namibia]                                               15
[Moçambique]                                            15
[Bénin]                                                 14
[Uganda]                                                13
[Nigeria]                                                9
[Zimbabwe]                                               8
[Burundi]                                                7
[Rwanda]                                                 7
[Madagasikara / Madagascar]                              7
[Sénégal]                                                7
[République démocratique du Congo]                       6
[Cameroun]                                               5
[مصر]                                                    5
[Malawi]                                                 5
[Mali]                                                   5
[Sierra Leone]                                           5
[Moçambique, Zambia]                                     3
[Soomaaliya الصومال]                                     3
[République démocratique du Congo, Zambia]               2
[Malawi, Zambia]                                         2
[Tanzania, Zambia]                                       2
[Guinée]                                                 2
[Lesotho]                                                2
[Liberia]                                                2
[Eswatini]                                               2
[Ghana, Kenya, Tanzania]                                 1
[Angola]                                                 1
[Uganda, Rwanda]                                         1
[Botswana]                                               1
[Burkina Faso]                                           1
[Gabon]                                                  1
[Sénégal, Guinée]                                        1
[تونس]                                                   1
[Sierra Leone, Moçambique]                               1
[Tanzania, Niger]                                        1
[Uganda, Nigeria]                                        1
[Burundi, Eswatini, Liberia]                             1
[Congo]                                                  1
[Tanzania, Moçambique, South Africa, Côte d’Ivoire]      1
[Gambia]                                                 1
[Burkina Faso, Ghana]                                    1
[Djibouti جيبوتي]                                        1
[Kenya, Tanzania]                                        1
[Kenya, Tanzania, Burkina Faso]                          1
[Tanzania, Kenya, Zambia]                                1
[Mauritanie موريتانيا]                                   1
[South Sudan جنوب السودان]                               1
[Togo]                                                   1
[Uganda, Malawi]                                         1
[Liberia, Zambia]                                        1
Name: count, dtype: int64

In [49]:
# translate the names of the countries

country_translations = {
    "Tanzania" : "Tanzania",
    "Zambia" : "Zambia",
    "République démocratique du Congo" : "Democratic Republic of the Congo",
    "Malawi" : "Malawi",
    "Moçambique" : "Mozambique",
    "Nigeria" : "Nigeria",
    "Uganda" : "Uganda",
    "South Africa" : "South Africa",
    "Namibia" : "Namibia",
    "Ghana" : "Ghana",
    "Kenya" : "Kenya",
    "Angola" : "Angola",
    "Bénin" : "Benin",
    "Rwanda" : "Rwanda",
    "Burundi" : "Burundi",
    "Zimbabwe" : "Zimbabwe",
    "Cameroun" : "Cameroon",
    "Botswana" : "Botswana",
    "Burkina Faso" : "Burkina Faso",
    "مصر" : "Egypt",
    "Gabon" : "Gabon",
    "Sénégal" : "Senegal",
    "Guinée" : "Guinea",
    "تونس" : "Tunisia",
    "Lesotho" : "Lesotho",
    "Madagasikara / Madagascar" : "Madagascar",
    "Liberia" : "Liberia",
    "Mali" : "Mali",
    "Sierra Leone" : "Sierra Leone",
    "Niger" : "Niger",
    "Eswatini" : "Swaziland",
    "Congo" : "Republic of Congo",
    "ⵍⵣⵣⴰⵢⴻⵔ الجزائر" : "Algeria",
    "Togo" : "Togo",
    "Côte d’Ivoire" : "Côte d’Ivoire",
    "Gambia" : "The Gambia",
    "Djibouti جيبوتي" : "Djibouti",
    "Mauritanie موريتانيا" : "Mauritania",
    "Soomaaliya الصومال" : "Somalia",
    "South Sudan جنوب السودان" : "South Sudan"
}

In [50]:
for index, _ in cleaned_data.iterrows():

    country_list = cleaned_data.loc[index, 'country']

    translated_country_list = []

    for country in country_list:

        translated_country = country_translations[country]
        translated_country_list.append(translated_country)
    
    cleaned_data.at[index, 'country'] = translated_country_list

In [51]:
for country in currently_identified:
    country_translated = country_translations[country] 

# checking the urls / titles / extracts for country mentions
for index, _ in cleaned_data.iterrows():

    country_list = cleaned_data.loc[index, 'country']
    url = cleaned_data.loc[index, 'url']
    url_lower = url.lower()

    title = cleaned_data.loc[index, 'title']
    title_lower = title.lower()

    extract = cleaned_data.loc[index, 'extract']
    extract_lower = extract.lower()

    if country_list == []:
        for country in currently_identified:
            country_lower = country.lower()

            if country_lower in url_lower:
                country_list.append(country)
                break

            elif country_lower in title_lower:
                country_list.append(country)
                break

            elif country_lower in extract_lower:
                country_list.append(country)
                break

    cleaned_data.at[index, 'country'] = country_list

In [52]:
cleaned_data['country'].value_counts()

country
[]                                                     136
[Tanzania]                                              59
[Zambia]                                                46
[Ghana]                                                 27
[Malawi]                                                22
[Kenya]                                                 20
[South Africa]                                          16
[Namibia]                                               16
[Mozambique]                                            15
[Nigeria]                                               14
[Uganda]                                                14
[Benin]                                                 14
[Burundi]                                               14
[Mali]                                                  14
[Zimbabwe]                                              10
[Sierra Leone]                                           9
[Rwanda]                                                 8
[Togo]                                                   8
[Madagascar]                                             7
[Senegal]                                                7
[Democratic Republic of the Congo]                       6
[Cameroon]                                               5
[Egypt]                                                  5
[Gabon]                                                  5
[Botswana]                                               4
[Lesotho]                                                4
[Mozambique, Zambia]                                     3
[Congo]                                                  3
[Liberia]                                                3
[Guinée]                                                 3
[Somalia]                                                3
[Democratic Republic of the Congo, Zambia]               2
[Malawi, Zambia]                                         2
[Tanzania, Zambia]                                       2
[Burkina Faso]                                           2
[Guinea]                                                 2
[Swaziland]                                              2
[Eswatini]                                               2
[Ghana, Kenya, Tanzania]                                 1
[Angola]                                                 1
[Uganda, Rwanda]                                         1
[Senegal, Guinea]                                        1
[Tunisia]                                                1
[Sierra Leone, Mozambique]                               1
[Tanzania, Niger]                                        1
[Uganda, Nigeria]                                        1
[Burundi, Swaziland, Liberia]                            1
[Republic of Congo]                                      1
[Niger]                                                  1
[Tanzania, Mozambique, South Africa, Côte d’Ivoire]      1
[The Gambia]                                             1
[Burkina Faso, Ghana]                                    1
[Djibouti]                                               1
[Kenya, Tanzania]                                        1
[Kenya, Tanzania, Burkina Faso]                          1
[Tanzania, Kenya, Zambia]                                1
[Mauritania]                                             1
[South Sudan]                                            1
[Uganda, Malawi]                                         1
[Liberia, Zambia]                                        1
Name: count, dtype: int64

In [237]:
df_url_country = cleaned_data[['country', 'url']]
df_url_country[df_url_country['country'].apply(lambda x: x == [])]['url'].value_counts()

url
https://www.unicri.org/sites/default/files/2019-10/IOM_PWA_REPORT_ENG_P2.pdf                                                                                             7
https://repository.gchumanrights.org/bitstreams/d2af9595-90ac-4d7f-887f-37c9b6bcef7f/download                                                                            7
https://www.amnesty.org/en/wp-content/uploads/2025/06/AFR0194872025ENGLISH.pdf                                                                                           6
https://spcommreports.ohchr.org/TMResultsBase/DownLoadPublicCommunicationFile?gId=30283                                                                                  5
https://www.underthesamesun.com/wp-content/uploads/2026/01/13-Attacks-of-PWA-2-page_01.23.2026.pdf                                                                       5
https://www.aa.com.tr/en/life/albinos-in-cameroon-threatened-due-to-witchcraft-superstitious-beliefs/2429227                                                             4
https://corbeaunews-centrafrique.org/centrafrique-les-albinos-toujours-face-a-lexclusion-et-aux-prejuges/                                                                4
https://www.amnesty.org/en/wp-content/uploads/2023/06/AFR3613962019ENGLISH.pdf                                                                                           4
https://digitalcommons.wcl.american.edu/cgi/viewcontent.cgi?article=2086&context=hrbrief                                                                                 3
https://repository.up.ac.za/bitstreams/da109116-58c9-4d8a-ba3c-881ea8e6621a/download                                                                                     3
https://angop.ao/en/noticias/grandes-reportagens/pessoas-com-albinismo-condenadas-pela-ignorancia/                                                                       3
https://upr-info.org/sites/default/files/country-document/2022-12/CBDH_Statement_Presession42_Benin.pdf                                                                  3
https://www.underthesamesun.com/wp-content/uploads/2026/01/Attacks-of-PWA-Extended-23.01.2026.pdf                                                                        3
https://www.ohchr.org/sites/default/files/documents/issues/albinism/2022-09-29/EoS_VisitMadagascar_30September2022.pdf                                                   3
https://news.abidjan.net/articles/411536/interview-coulibaly-mamidou-lalbinos-denonce-nous-sommes-en-danger-en-periodes-electorales                                      3
https://www.sitesofconscience.org/extraordinary-women-hadjiratou-bah/                                                                                                    3
https://www.amnesty.org/en/latest/campaigns/2026/07/ending-attacks-against-persons-with-albinism/                                                                        3
https://w3.cridem.org/imprimable.php?article=746226                                                                                                                      3
https://360mozambique.com/development/government-reaffirms-protection-of-the-rights-of-around-30000-people-with-albinism-in-the-country/                                 3
https://lequotidien.sn/manque-de-prise-en-charge-stigmatisation-la-lutte-brulante-des-albinos/                                                                           3
https://www.engagesalone.org/health-lifestyle/living-with-albinism-the-burden-of-discrimination-neglect-and-severe-health-risks/                                         3
https://www.institut-fuer-menschenrechte.de/fileadmin/Redaktion/PDF/DB_ius/CRPD_18082017_X_v_Tansania_ENG.pdf                                                            3
https://africaalbinismnetwork.org/wp-content/uploads/2023/11/Joint-submission-in-Response-to-the-Call-for-Inputs-Persons-with-Albinism-and-the-Right-to-Education.pdf    3
https://link.springer.com/article/10.1186/s12914-018-0144-8                                                                                                              3
https://www.dailymaverick.co.za/opinionista/2025-02-27-landmark-court-victory-for-human-rights-of-people-with-albinism-in-africa/                                        2
https://docs.un.org/en/A/74/184?direct=true                                                                                                                              2
https://www.africanews.com/2021/12/06/cameroon-s-albinos-threatened-by-magic-and-superstition/                                                                           2
https://www.voanews.com/a/cameroons-albinos-fight-prejudice-106312068/156587.html                                                                                        2
https://documents.un.org/doc/undoc/gen/n23/205/22/pdf/n2320522.pdf                                                                                                       2
https://bettercarenetwork.org/sites/default/files/2024-08/a_79_175-en_1.pdf                                                                                              2
https://www.state.gov/report/custom/1948f83df1                                                                                                                           2
https://spcommreports.ohchr.org/TMResultsBase/DownLoadPublicCommunicationFile?gId=28629                                                                                  2
https://initiativesnews.com/journeee-de-sensibilisation-a-lalbinisme-unis-pour-faire-entendre-notre-voix/                                                                2
https://www.kigaliup.net/2022/06/15/persons-with-albinism-decry-on-lack-of-sunscreen-products/                                                                           2
https://www.gov.za/news/media-advisories/government-activities/deputy-minister-hendrietta-bogopane-zulu-hosts-un                                                         2
https://africaalbinismnetwork.org/wp-content/uploads/2023/11/Access-to-health-by-persons-with-albinism.pdf                                                               2
https://www.ugnewsline.com/nudipu-albinism-umbrella-demand-urgent-action-over-police-negligence-in-kyotera-albinism-attack-case/                                         2
https://ihrp.law.utoronto.ca/un-advocacy-cocktail-parties-advocating-rights-persons-albinism                                                                             2
https://link.springer.com/article/10.1007/s12687-026-00872-0                                                                                                             1
https://www.un.org/en/observances/albinism-day/albinism-and-human-rights                                                                                                 1
https://www.ohchr.org/sites/default/files/2022-12/Albinism-Worldwide-Report-2021-EN.pdf                                                                                  1
https://www.ungeneva.org/en/news-media/meeting-summary/2022/08/experts-committee-elimination-racial-discrimination-commend                                               1
https://www.africa-press.net/cape-verde/all-news/albinism-stigma-myths-and-ritualistic-fears                                                                             1
https://www.icj.org/wp-content/uploads/2025/03/ICJ-OS-ID-IE-Albinism-HRC-58.pdf                                                                                          1
https://www.chr.up.ac.za/news-archive/2018/485-pan-african-parliament-takes-a-strong-stance-on-violence-against-persons-with-albinism-in-africa                          1
https://zap.aeiou.pt/os-albinos-da-guine-bissau-querem-protecao-do-estado-569031                                                                                         1
https://www.hi-canada.org/en/news/aicha-and-friends-show-us-the-joy-of-inclusion-                                                                                        1
https://www.ohchr.org/en/press-releases/2022/02/madagascar-un-experts-urge-protection-people-albinism-amid-attacks                                                       1
https://albinism.ohchr.org/story-salif-keita.html                                                                                                                        1
https://press.cridem.org/imprimable.php?article=676482                                                                                                                   1
https://www.hrw.org/video-photos/video/2019/06/13/cradle-grave-discrimination-against-persons-albinism-mozambique                                                        1
https://www.nytimes.com/interactive/2017/05/05/sunday-review/albinos-in-mozambique.html                                                                                  1
https://www.lesahel.org/journee-mondiale-de-sensibilisation-a-lalbinisme-lever-les-prejuges-pour-une-societe-plus-inclusive/                                             1
https://www.pureafricanews.com/2025/07/15/living-in-the-shadows-mothers-of-children-with-albinism-face-societal-rejection/                                               1
https://www.newvision.co.ug/category/family/govt-urged-to-do-more-to-protect-persons-with-NV_234652_062026                                                               1
https://www.ohchr.org/sites/default/files/2025-02/a-79-175-annex.pdf                                                                                                     1
Name: count, dtype: int64

In [238]:
cleaned_data['country'].value_counts()

country
[]                                                     136
[Tanzania]                                              59
[Zambia]                                                46
[Ghana]                                                 27
[Malawi]                                                22
[Kenya]                                                 20
[South Africa]                                          16
[Namibia]                                               16
[Mozambique]                                            15
[Nigeria]                                               14
[Uganda]                                                14
[Benin]                                                 14
[Burundi]                                               14
[Mali]                                                  14
[Zimbabwe]                                              10
[Sierra Leone]                                           9
[Rwanda]                                                 8
[Togo]                                                   8
[Madagascar]                                             7
[Senegal]                                                7
[Democratic Republic of the Congo]                       6
[Cameroon]                                               5
[Egypt]                                                  5
[Gabon]                                                  5
[Botswana]                                               4
[Lesotho]                                                4
[Mozambique, Zambia]                                     3
[Congo]                                                  3
[Liberia]                                                3
[Guinée]                                                 3
[Somalia]                                                3
[Democratic Republic of the Congo, Zambia]               2
[Malawi, Zambia]                                         2
[Tanzania, Zambia]                                       2
[Burkina Faso]                                           2
[Guinea]                                                 2
[Swaziland]                                              2
[Eswatini]                                               2
[Ghana, Kenya, Tanzania]                                 1
[Angola]                                                 1
[Uganda, Rwanda]                                         1
[Senegal, Guinea]                                        1
[Tunisia]                                                1
[Sierra Leone, Mozambique]                               1
[Tanzania, Niger]                                        1
[Uganda, Nigeria]                                        1
[Burundi, Swaziland, Liberia]                            1
[Republic of Congo]                                      1
[Niger]                                                  1
[Tanzania, Mozambique, South Africa, Côte d’Ivoire]      1
[The Gambia]                                             1
[Burkina Faso, Ghana]                                    1
[Djibouti]                                               1
[Kenya, Tanzania]                                        1
[Kenya, Tanzania, Burkina Faso]                          1
[Tanzania, Kenya, Zambia]                                1
[Mauritania]                                             1
[South Sudan]                                            1
[Uganda, Malawi]                                         1
[Liberia, Zambia]                                        1
Name: count, dtype: int64

In [54]:
# filling country for extract with no country
cleaned_data[cleaned_data['country'].apply(lambda x: x == [])].index.tolist()

[2,
 3,
 4,
 8,
 9,
 10,
 13,
 15,
 16,
 51,
 52,
 53,
 54,
 55,
 76,
 77,
 78,
 80,
 92,
 94,
 98,
 99,
 125,
 126,
 129,
 130,
 131,
 132,
 134,
 136,
 138,
 145,
 146,
 147,
 156,
 158,
 159,
 160,
 177,
 179,
 180,
 181,
 182,
 183,
 184,
 186,
 187,
 188,
 189,
 190,
 191,
 237,
 238,
 251,
 305,
 306,
 307,
 309,
 311,
 313,
 314,
 315,
 320,
 327,
 330,
 333,
 338,
 502,
 504,
 507,
 512,
 517,
 520,
 521,
 522,
 524,
 525,
 526,
 553,
 554,
 555,
 556,
 557,
 585,
 587,
 589,
 591,
 592,
 594,
 603,
 604,
 605,
 606,
 608,
 609,
 617,
 619,
 621,
 622,
 623,
 624,
 625,
 626,
 627,
 628,
 629,
 630,
 635,
 645,
 649,
 650,
 658,
 659,
 660,
 661,
 662,
 663,
 691,
 692,
 695,
 699,
 714,
 715,
 716,
 740,
 743,
 746,
 776,
 777,
 779,
 784,
 785,
 786,
 788,
 789,
 790]

In [55]:
cleaned_data.at[13, "country"] = ["Zambia"]
cleaned_data.at[53, "country"] = ["Mozambique"]
cleaned_data.at[98, "country"] = ["Zambia"]
cleaned_data.at[99, "country"] = ["Zambia"]
cleaned_data.at[129, "country"] = ["Mozambique"]
cleaned_data.at[130, "country"] = ["Mozambique"]
cleaned_data.at[131, "country"] = ["Mozambique"]
cleaned_data.at[132, "country"] = ["Mozambique"]
cleaned_data.at[134, "country"] = ["Mozambique"]
cleaned_data.at[136, "country"] = ["Mozambique"]
cleaned_data.at[138, "country"] = ["Mozambique"]
cleaned_data.at[145, "country"] = ["Angola"]
cleaned_data.at[146, "country"] = ["Angola"]
cleaned_data.at[147, "country"] = ["Angola"]
cleaned_data.at[156, "country"] = ["Benin"]
cleaned_data.at[158, "country"] = ["Benin"]
cleaned_data.at[159, "country"] = ["Benin"]
cleaned_data.at[160, "country"] = ["Benin"]
cleaned_data.at[177, "country"] = ['Cape Verde']
cleaned_data.at[177, "country"] = ['Cape Verde']
cleaned_data.at[179, "country"] = ['Cameroon']
cleaned_data.at[180, "country"] = ['Cameroon']
cleaned_data.at[181, "country"] = ['Cameroon']
cleaned_data.at[182, "country"] = ['Cameroon']
cleaned_data.at[183, "country"] = ['Cameroon']
cleaned_data.at[184, "country"] = ['Cameroon']
cleaned_data.at[185, "country"] = ['Cameroon']
cleaned_data.at[186, "country"] = ['Cameroon']
cleaned_data.at[187, "country"] = ['Cameroon']
cleaned_data.at[188, "country"] = ['Central African Republic']
cleaned_data.at[189, "country"] = ['Central African Republic']
cleaned_data.at[190, "country"] = ['Tanzania']
cleaned_data.at[191, "country"] = ['Central African Republic']
cleaned_data.at[237, "country"] = ['Madagascar']
cleaned_data.at[238, "country"] = ['Madagascar']
cleaned_data.at[251, "country"] = ["Mozambique"]
cleaned_data.at[306, "country"] = ["Madagascar"]
cleaned_data.at[307, "country"] = ["Madagascar"]
cleaned_data.at[308, "country"] = ["Madagascar"]
cleaned_data.at[309, "country"] = ["Madagascar"]
cleaned_data.at[313, "country"] = ["Côte d'Ivoire"]
cleaned_data.at[314, "country"] = ["Côte d'Ivoire"]
cleaned_data.at[315, "country"] = ["Côte d'Ivoire"]
cleaned_data.at[320, "country"] = ["Cameroon"]
cleaned_data.at[327, "country"] = ["Côte d'Ivoire"]
cleaned_data.at[330, "country"] = ["Madagascar"]
cleaned_data.at[333, "country"] = ["Mozambique"]
cleaned_data.at[338, "country"] = ["Senegal"]
cleaned_data.at[512, "country"] = ["Mozambique"]
cleaned_data.at[522, "country"] = ["South Africa"]
cleaned_data.at[525, "country"] = ["Democratic Republic of the Congo"]
cleaned_data.at[556, "country"] = ["Guinea-Bissau"]
cleaned_data.at[587, "country"] = ["Tanzania"]
cleaned_data.at[594, "country"] = ["Madagascar"]
cleaned_data.at[603, "country"] = ["Malawi"]
cleaned_data.at[605, "country"] = ["Malawi"]
cleaned_data.at[619, "country"] = ["Mauritania"]
cleaned_data.at[621, "country"] = ["Mauritania"]
cleaned_data.at[622, "country"] = ["Mauritania"]
cleaned_data.at[623, "country"] = ["Mauritania"]
cleaned_data.at[624, "country"] = ["Mauritania"]
cleaned_data.at[626, "country"] = ["Mauritania"]
cleaned_data.at[627, "country"] = ["Mauritania"]
cleaned_data.at[629, "country"] = ["Mauritania"]
cleaned_data.at[649, "country"] = ["Rwanda"]
cleaned_data.at[650, "country"] = ["Rwanda"]
cleaned_data.at[658, "country"] = ["Senegal"]
cleaned_data.at[659, "country"] = ["Senegal"]
cleaned_data.at[660, "country"] = ["Senegal"]
cleaned_data.at[715, "country"] = ["Tanzania"]
cleaned_data.at[716, "country"] = ["Tanzania"]
cleaned_data.at[740, "country"] = ["Uganda"]
cleaned_data.at[743, "country"] = ["Uganda"]
cleaned_data.at[746, "country"] = ["Uganda"]

In [56]:
cleaned_data['country'].value_counts()

country
[]                                 65
[Tanzania]                         63
[Zambia]                           49
[Ghana]                            27
[Mozambique]                       26
                                   ..
[Kenya, Tanzania, Burkina Faso]     1
[Tanzania, Kenya, Zambia]           1
[South Sudan]                       1
[Uganda, Malawi]                    1
[Liberia, Zambia]                   1
Name: count, Length: 63, dtype: int64

In [57]:
cleaned_data[cleaned_data['country'].apply(lambda x: 'Democratic Republic of the Congo' in x)]

,url,title,authors,date,extract,country,theme,to_watch
18,https://africaalbinismnetwork.org/wp-content/u...,ACCESS TO JUSTICE FOR PERSONS WITH ALBINISM: C...,Albinism for Change in Africa Initiative Organ...,March 2025,"According to albinism groups, in March 2014, t...","[Democratic Republic of the Congo, Zambia]",['right to life'],True
19,https://africaalbinismnetwork.org/wp-content/u...,ACCESS TO JUSTICE FOR PERSONS WITH ALBINISM: C...,Albinism for Change in Africa Initiative Organ...,March 2025,Media reported the abandonment of an infant wi...,"[Democratic Republic of the Congo, Zambia]","['right to life', 'right to health']",False
93,https://www.un.org/en/observances/albinism-day...,Albinism and Human Rights,United Nations,NaN,A caregiver attends to an abandoned toddler wi...,[Democratic Republic of the Congo],[],False
222,https://www.underthesamesun.com/wp-content/upl...,RE: PERSONS WITH ALBINISM (Extended Version),Under The Same Sun (UTSS),"January 23, 2026","On Wednesday, February 1, 2023, J.K., a 5-year...",[Democratic Republic of the Congo],['right to life'],True
223,https://www.underthesamesun.com/wp-content/upl...,RE: PERSONS WITH ALBINISM (Extended Version),Under The Same Sun (UTSS),"January 23, 2026","On September 28, 2021, in Bukavu, DR Congo, a ...",[Democratic Republic of the Congo],['right to life'],False
224,https://www.underthesamesun.com/wp-content/upl...,RE: PERSONS WITH ALBINISM (Extended Version),Under The Same Sun (UTSS),"January 23, 2026","On March 16, 2021, there was an attempt to exh...",[Democratic Republic of the Congo],['right to health'],False
225,https://www.underthesamesun.com/wp-content/upl...,RE: PERSONS WITH ALBINISM (Extended Version),Under The Same Sun (UTSS),"January 23, 2026","In the early hours of March 25, 2019, the grav...",[Democratic Republic of the Congo],[],False
312,https://www.africanews.com/2021/11/21/congo-br...,Congo: Brazzaville clinic helps embattled albi...,NaN,13/08/2024,"""I'm loved in my family, but in my area there ...",[Democratic Republic of the Congo],[],False
525,https://repository.gchumanrights.org/bitstream...,"Demystifying Albinism: An analysis of legal, s...",Giorgio Caviglia,2011 - 2012,"In November of 2008, a man was arrested in DRC...",[Democratic Republic of the Congo],['right to life'],True

In [58]:
cleaned_data[cleaned_data['country'].apply(lambda x: 'Guinea' in x)]

,url,title,authors,date,extract,country,theme,to_watch
230,https://www.underthesamesun.com/wp-content/upl...,RE: PERSONS WITH ALBINISM (Extended Version),Under The Same Sun (UTSS),"January 23, 2026","On a Sunday in September of 2010, at the area ...","[Senegal, Guinea]",['right to life'],False
231,https://www.underthesamesun.com/wp-content/upl...,RE: PERSONS WITH ALBINISM (Extended Version),Under The Same Sun (UTSS),"January 23, 2026","On May 17, 2017, a four-year-old girl with alb...",[Guinea],['right to life'],True
326,https://www.underthesamesun.com/wp-content/upl...,Reported Attacks of Persons with Albinism (PWA...,UTSS,"January 23, 2026","Guinea, 16 reports: 5 killings / 6 survivors /...",[Guinea],['right to life'],False

In [85]:
cleaned_data.at[312, "country"] = ["Republic of Congo"]
cleaned_data.at[221, "country"] = ["Republic of Congo"]
cleaned_data.at[321, "country"] = ["Republic of Congo"]

## theme

In [77]:
cleaned_data['theme'] = cleaned_data["theme"].apply(ast.literal_eval)

ValueError: malformed node or string: ['right to life']

In [ ]:
len(cleaned_data)

556

In [ ]:
# check how many have no theme
df_url_theme = cleaned_data[['theme', 'url']]
len(df_url_theme[df_url_theme['theme'].apply(lambda x: x == [])])

165

In [ ]:
# check how many have violence in their theme
len(df_url_theme[df_url_theme['theme'].apply(lambda x: "right to life" in x)])

271

In [ ]:
# check how many only have violence as their theme
len(df_url_theme[df_url_theme['theme'].apply(lambda x: x == ["right to life"])])

212

In [ ]:
len(df_url_theme[df_url_theme['theme'].apply(lambda x: "right to education" in x)])

19

In [ ]:
len(df_url_theme[df_url_theme['theme'].apply(lambda x: "right to health" in x)])

93

In [ ]:
len(df_url_theme[df_url_theme['theme'].apply(lambda x: "right to work" in x)])

10

In [ ]:
len(df_url_theme[df_url_theme['theme'].apply(lambda x: "access to justice" in x)])

26

In [ ]:
len(df_url_theme[df_url_theme['theme'].apply(lambda x: "adequate standard of living" in x)])

66

In [ ]:
len(df_url_theme[df_url_theme['theme'].apply(lambda x: len(x) == 1)])

306

In [ ]:
len(df_url_theme[df_url_theme['theme'].apply(lambda x: len(x) == 2)])

76

In [ ]:
len(df_url_theme[df_url_theme['theme'].apply(lambda x: len(x) > 2)])

9

In [ ]:
# for later: check the ones that have more than 2 themes identified

In [86]:
cleaned_data.to_csv("full_cleaned_dataset.csv")